/* Generated by tools/export_model.py; do not edit. */
#ifndef NNC_GENERATED_EXAMPLE_MODEL_H
#define NNC_GENERATED_EXAMPLE_MODEL_H

#include "nnc/nn.h"

#define EXAMPLE_MODEL_LAYER_COUNT 2U
#define EXAMPLE_MODEL_WORKSPACE_FLOATS 4U

static const float example_model_layer_0_weights[] = {
    0.5F, 0.25F, -0.4F, 0.8F
};

static const float example_model_layer_0_biases[] = {
    0.1F, -0.2F
};

static const float example_model_layer_1_weights[] = {
    1.2F, -0.7F
};

static const float example_model_layer_1_biases[] = {
    0.05F
};

static const nn_dense_layer_t example_model_layers[EXAMPLE_MODEL_LAYER_COUNT] = {
    {
        .input_count = 2U,
        .output_count = 2U,
        .weights = example_model_layer_0_weights,
        .biases = example_model_layer_0_biases,
        .activation = NN_ACTIVATION_SIGMOID
    },
    {
        .input_count = 2U,
        .output_count = 1U,
        .weights = example_model_layer_1_weights,
        .biases = example_model_layer_1_biases,
        .activation = NN_ACTIVATION_SIGMOID
    },
};

#endif /* NNC_GENERATED_EXAMPLE_MODEL_H */
