/* Generated by tools/export_model.py; do not edit. */
#ifndef NNC_GENERATED_TRAINED_XOR_H
#define NNC_GENERATED_TRAINED_XOR_H

#include "nnc/nn.h"

#define TRAINED_XOR_LAYER_COUNT 2U
#define TRAINED_XOR_WORKSPACE_FLOATS 8U

static const float trained_xor_layer_0_weights[] = {
    -2.96870312F, -2.96690147F, 2.56224943F, -3.98994125F, 4.10399662F, -2.7467042F,
    0.474840763F, 1.15029763F
};

static const float trained_xor_layer_0_biases[] = {
    0.640961692F, -0.809378144F, 0.927576131F, -1.14637085F
};

static const float trained_xor_layer_1_weights[] = {
    -5.18312751F, 6.32523813F, -6.85265703F, -1.7538997F
};

static const float trained_xor_layer_1_biases[] = {
    1.78299003F
};

static const nn_dense_layer_t trained_xor_layers[TRAINED_XOR_LAYER_COUNT] = {
    {
        .input_count = 2U,
        .output_count = 4U,
        .weights = trained_xor_layer_0_weights,
        .biases = trained_xor_layer_0_biases,
        .activation = NN_ACTIVATION_TANH
    },
    {
        .input_count = 4U,
        .output_count = 1U,
        .weights = trained_xor_layer_1_weights,
        .biases = trained_xor_layer_1_biases,
        .activation = NN_ACTIVATION_SIGMOID
    },
};

#endif /* NNC_GENERATED_TRAINED_XOR_H */
