"""Render a validated NN-C model as a deterministic C header."""

from __future__ import annotations

import re
from collections.abc import Sequence

from nnc_model import DenseLayer, ModelError


ACTIVATIONS = {
    "linear": "NN_ACTIVATION_LINEAR",
    "relu": "NN_ACTIVATION_RELU",
    "sigmoid": "NN_ACTIVATION_SIGMOID",
    "tanh": "NN_ACTIVATION_TANH",
}
IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _literal(value: float) -> str:
    value = 0.0 if value == 0.0 else value
    text = format(value, ".9g")
    if "." not in text and "e" not in text.lower():
        text += ".0"
    return text + "F"


def _values(values: Sequence[float]) -> list[str]:
    lines = []
    for start in range(0, len(values), 6):
        chunk = ", ".join(_literal(value) for value in values[start : start + 6])
        lines.append(f"    {chunk}{',' if start + 6 < len(values) else ''}")
    return lines


def render_header(layers: Sequence[DenseLayer], symbol: str) -> str:
    if not IDENTIFIER.fullmatch(symbol):
        raise ModelError("symbol must be a valid C identifier")

    upper = symbol.upper()
    lower = symbol.lower()
    guard = f"NNC_GENERATED_{upper}_H"
    workspace = 2 * max(layer.outputs for layer in layers)
    lines = [
        "/* Generated by tools/export_model.py; do not edit. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "nnc/nn.h"',
        "",
        f"#define {upper}_LAYER_COUNT {len(layers)}U",
        f"#define {upper}_WORKSPACE_FLOATS {workspace}U",
        "",
    ]

    for index, layer in enumerate(layers):
        lines.append(f"static const float {lower}_layer_{index}_weights[] = {{")
        lines.extend(_values(layer.weights))
        lines.extend(["};", ""])
        lines.append(f"static const float {lower}_layer_{index}_biases[] = {{")
        lines.extend(_values(layer.biases))
        lines.extend(["};", ""])

    lines.append(
        f"static const nn_dense_layer_t {lower}_layers"
        f"[{upper}_LAYER_COUNT] = {{"
    )
    for index, layer in enumerate(layers):
        lines.extend(
            [
                "    {",
                f"        .input_count = {layer.inputs}U,",
                f"        .output_count = {layer.outputs}U,",
                f"        .weights = {lower}_layer_{index}_weights,",
                f"        .biases = {lower}_layer_{index}_biases,",
                f"        .activation = {ACTIVATIONS[layer.activation]}",
                "    },",
            ]
        )
    lines.extend(["};", "", f"#endif /* {guard} */", ""])
    return "\n".join(lines)
